### ISSUE TITLE
no locks?

### ISSUE THREAD

**Issue by matkatmusic** [FigBug/FileSystemWatcher#1]
https://github.com/FigBug/FileSystemWatcher/blob/5b92d98c15ea9b5262b9e188d801eca364eb19dc/FileSystemWatcher/FileSystemWatcher.cpp#L195

why no locks?   the usual juce pattern is to lock when adding/removing listeners so the listenerList doesn't get changed while it's calling the listener callback.   Also, nice meeting you at NAMM!

**Comment by FigBug** [comment]
Everything happens on main thread so shouldn't need locks. I think ListenerList::call() is smart enough to watch the list for changes will do callbacks. But you really shouldn't modify the list during the callback or you can cause other listeners to get skipped.
